import mongoose from 'mongoose';
import dotenv from 'dotenv';
import { connectDatabase } from '../config/database.js';
import Subject from '../models/Subject.js';
import Question from '../models/Question.js';

dotenv.config();

const seedHistoryPart2 = async () => {
  try {
    await connectDatabase();
    let historySubject = await Subject.findOne({ name: 'History' });
    if (!historySubject) {
      historySubject = await Subject.create({ name: 'History', nameAr: 'التاريخ', description: 'أسئلة تاريخية', color: '#ef4444' });
    }
    const subjectId = historySubject._id;

    console.log('🌱 Adding History Questions Part 2...');

    // More Four Options Questions (26-50)
    const fourOptionsQuestions = [
      { text: "من هو ملك فرنسا الذي أُعدم بالمقصلة عام 1793؟", options: [{ id: "1", text: "لويس الرابع عشر", isCorrect: false }, { id: "2", text: "لويس السادس عشر", isCorrect: true }, { id: "3", text: "لويس الثامن عشر", isCorrect: false }, { id: "4", text: "نابليون الثالث", isCorrect: false }], difficulty: "medium" },
      { text: "أي معركة هزم فيها هانيبال الرومان عام 216 ق.م؟", options: [{ id: "1", text: "معركة زاما", isCorrect: false }, { id: "2", text: "معركة كاناي", isCorrect: true }, { id: "3", text: "معركة تريبيا", isCorrect: false }, { id: "4", text: "معركة بحيرة تراسيمين", isCorrect: false }], difficulty: "hard" },
      { text: "من أسس مدينة بغداد عام 762 م؟", options: [{ id: "1", text: "هارون الرشيد", isCorrect: false }, { id: "2", text: "أبو جعفر المنصور", isCorrect: true }, { id: "3", text: "المأمون", isCorrect: false }, { id: "4", text: "المعتصم", isCorrect: false }], difficulty: "medium" },
      { text: "متى تم إسقاط القنبلة الذرية على هيروشيما؟", options: [{ id: "1", text: "1944", isCorrect: false }, { id: "2", text: "1945", isCorrect: true }, { id: "3", text: "1946", isCorrect: false }, { id: "4", text: "1950", isCorrect: false }], difficulty: "easy" },
      { text: "من كان قائد الثورة البلشفية؟", options: [{ id: "1", text: "تروتسكي", isCorrect: false }, { id: "2", text: "لينين", isCorrect: true }, { id: "3", text: "ستالين", isCorrect: false }, { id: "4", text: "كارل ماركس", isCorrect: false }], difficulty: "medium" },
      { text: "أي دولة استعمرت الهند لأطول فترة؟", options: [{ id: "1", text: "البرتغال", isCorrect: false }, { id: "2", text: "فرنسا", isCorrect: false }, { id: "3", text: "بريطانيا", isCorrect: true }, { id: "4", text: "هولندا", isCorrect: false }], difficulty: "easy" },
      { text: "من هو 'الخليفة الراشد' الرابع؟", options: [{ id: "1", text: "أبو بكر", isCorrect: false }, { id: "2", text: "عمر", isCorrect: false }, { id: "3", text: "عثمان", isCorrect: false }, { id: "4", text: "علي بن أبي طالب", isCorrect: true }], difficulty: "easy" },
      { text: "متى اكتُشفت القارة القطبية الجنوبية؟", options: [{ id: "1", text: "1773", isCorrect: false }, { id: "2", text: "1820", isCorrect: true }, { id: "3", text: "1911", isCorrect: false }, { id: "4", text: "1492", isCorrect: false }], difficulty: "hard" },
      { text: "من كتب 'تاريخ الحروب البيلوبونيزية'؟", options: [{ id: "1", text: "هيرودوت", isCorrect: false }, { id: "2", text: "ثوكيديديس", isCorrect: true }, { id: "3", text: "كزينوفون", isCorrect: false }, { id: "4", text: "بلوتارخوس", isCorrect: false }], difficulty: "hard" },
      { text: "أي حدث بدأ الحرب العالمية الأولى؟", options: [{ id: "1", text: "اغتيال الأرشيدوق فرانز فرديناند", isCorrect: true }, { id: "2", text: "غرق السفينة لوسيتانيا", isCorrect: false }, { id: "3", text: "ثورة روسيا", isCorrect: false }, { id: "4", text: "معركة السوم", isCorrect: false }], difficulty: "medium" },
      { text: "من هو مكتشف البنسلين؟", options: [{ id: "1", text: "لويس باستور", isCorrect: false }, { id: "2", text: "ألكسندر فليمنج", isCorrect: true }, { id: "3", text: "روبرت كوخ", isCorrect: false }, { id: "4", text: "جوناس سالك", isCorrect: false }], difficulty: "medium" },
      { text: "متى تم توحيد ألمانيا تحت بسمارك؟", options: [{ id: "1", text: "1866", isCorrect: false }, { id: "2", text: "1871", isCorrect: true }, { id: "3", text: "1918", isCorrect: false }, { id: "4", text: "1945", isCorrect: false }], difficulty: "medium" },
      { text: "أي إمبراطور روماني جعل المسيحية ديناً رسمياً؟", options: [{ id: "1", text: "قسطنطين الكبير", isCorrect: false }, { id: "2", text: "نيرون", isCorrect: false }, { id: "3", text: "أوغسطس", isCorrect: false }, { id: "4", text: "ثيودوسيوس الأول", isCorrect: true }], difficulty: "hard" },
      { text: "من قاد حملة نابليون على مصر؟", options: [{ id: "1", text: "نابليون بنفسه", isCorrect: true }, { id: "2", text: "كليبر", isCorrect: false }, { id: "3", text: "مورا", isCorrect: false }, { id: "4", text: "ديسيه", isCorrect: false }], difficulty: "easy" },
      { text: "متى انتهت الحرب الباردة تقريباً؟", options: [{ id: "1", text: "1985", isCorrect: false }, { id: "2", text: "1991", isCorrect: true }, { id: "3", text: "1979", isCorrect: false }, { id: "4", text: "2000", isCorrect: false }], difficulty: "easy" },
      { text: "أي مدينة كانت مركز عصر النهضة؟", options: [{ id: "1", text: "روما", isCorrect: false }, { id: "2", text: "فلورنسا", isCorrect: true }, { id: "3", text: "البندقية", isCorrect: false }, { id: "4", text: "باريس", isCorrect: false }], difficulty: "medium" },
      { text: "من هو الفيلسوف الذي قال 'أنا أفكر إذن أنا موجود'؟", options: [{ id: "1", text: "ديكارت", isCorrect: true }, { id: "2", text: "كانط", isCorrect: false }, { id: "3", text: "هيغل", isCorrect: false }, { id: "4", text: "نيتشه", isCorrect: false }], difficulty: "medium" },
      { text: "متى تمت أول رحلة فضائية مأهولة؟", options: [{ id: "1", text: "1957", isCorrect: false }, { id: "2", text: "1961", isCorrect: true }, { id: "3", text: "1969", isCorrect: false }, { id: "4", text: "1971", isCorrect: false }], difficulty: "medium" },
      { text: "أي معركة انتصر فيها المسلمون على الصينيين؟", options: [{ id: "1", text: "معركة الطالس", isCorrect: true }, { id: "2", text: "معركة بلاط الشهداء", isCorrect: false }, { id: "3", text: "معركة القادسية", isCorrect: false }, { id: "4", text: "معركة اليرموك", isCorrect: false }], difficulty: "hard" },
      { text: "من هو آخر إمبراطور روماني غربي؟", options: [{ id: "1", text: "رومولوس أوغسطس", isCorrect: true }, { id: "2", text: "يوليوس نيبوس", isCorrect: false }, { id: "3", text: "قسطنطين الحادي عشر", isCorrect: false }, { id: "4", text: "جستنيان", isCorrect: false }], difficulty: "hard" },
      { text: "متى وقعت كارثة تشيرنوبل؟", options: [{ id: "1", text: "1984", isCorrect: false }, { id: "2", text: "1986", isCorrect: true }, { id: "3", text: "1988", isCorrect: false }, { id: "4", text: "1991", isCorrect: false }], difficulty: "easy" },
      { text: "من كان قائد المقاومة الفرنسية في الحرب العالمية الثانية؟", options: [{ id: "1", text: "شارل ديغول", isCorrect: true }, { id: "2", text: "جان مولان", isCorrect: false }, { id: "3", text: "فيليب بيتان", isCorrect: false }, { id: "4", text: "موريس جاميلان", isCorrect: false }], difficulty: "medium" },
      { text: "أي دولة كانت تُعرف بـ'رجل أوروبا المريض'؟", options: [{ id: "1", text: "النمسا-المجر", isCorrect: false }, { id: "2", text: "الإمبراطورية العثمانية", isCorrect: true }, { id: "3", text: "روسيا", isCorrect: false }, { id: "4", text: "ألمانيا", isCorrect: false }], difficulty: "medium" },
      { text: "من اخترع الطباعة بالحروف المتحركة في أوروبا؟", options: [{ id: "1", text: "يوهانس غوتنبرغ", isCorrect: true }, { id: "2", text: "ليوناردو دا فينشي", isCorrect: false }, { id: "3", text: "غاليليو", isCorrect: false }, { id: "4", text: "كوبرنيكوس", isCorrect: false }], difficulty: "easy" },
      { text: "متى حصلت الهند على استقلالها من بريطانيا؟", options: [{ id: "1", text: "1945", isCorrect: false }, { id: "2", text: "1947", isCorrect: true }, { id: "3", text: "1950", isCorrect: false }, { id: "4", text: "1960", isCorrect: false }], difficulty: "easy" },
    ].map(q => ({ text: q.text, subjectId, questionTypeId: 'four-options', options: q.options, difficulty: q.difficulty as 'easy' | 'medium' | 'hard', points: q.difficulty === 'easy' ? 10 : q.difficulty === 'medium' ? 15 : 20, timeLimit: 30 }));

    // More Order Questions (16-35)
    const orderQuestions = [
      { text: "رتب أحداث تاريخ الصين:", orderItems: [{ id: "1", text: "ثورة شينهاي (1911)", correctPosition: 1 }, { id: "2", text: "إعلان جمهورية الصين (1912)", correctPosition: 2 }, { id: "3", text: "الحرب الصينية اليابانية (1937)", correctPosition: 3 }, { id: "4", text: "تأسيس جمهورية الصين الشعبية (1949)", correctPosition: 4 }], difficulty: "hard" },
      { text: "رتب المعارك اليونانية الفارسية:", orderItems: [{ id: "1", text: "معركة ثرموبيل (480 ق.م)", correctPosition: 1 }, { id: "2", text: "معركة سالاميس (480 ق.م)", correctPosition: 2 }, { id: "3", text: "معركة بلاتيا (479 ق.م)", correctPosition: 3 }, { id: "4", text: "حرب البيلوبونيز (431 ق.م)", correctPosition: 4 }], difficulty: "hard" },
      { text: "رتب نهاية الحرب العالمية الثانية:", orderItems: [{ id: "1", text: "إسقاط القنبلة على ناغازاكي", correctPosition: 1 }, { id: "2", text: "استسلام اليابان", correctPosition: 2 }, { id: "3", text: "إعلان الأمم المتحدة", correctPosition: 3 }, { id: "4", text: "بدء الحرب الباردة", correctPosition: 4 }], difficulty: "medium" },
      { text: "رتب تاريخ الدولة الأيوبية:", orderItems: [{ id: "1", text: "صلاح الدين يتولى الوزارة (1169)", correctPosition: 1 }, { id: "2", text: "سقوط الدولة الفاطمية (1171)", correctPosition: 2 }, { id: "3", text: "معركة حطين (1187)", correctPosition: 3 }, { id: "4", text: "استعادة القدس (1187)", correctPosition: 4 }], difficulty: "hard" },
      { text: "رتب تطور البارود والمدافع:", orderItems: [{ id: "1", text: "اختراع البارود في الصين", correctPosition: 1 }, { id: "2", text: "استخدام المدافع في أوروبا", correctPosition: 2 }, { id: "3", text: "معركة كريسي (1346)", correctPosition: 3 }, { id: "4", text: "سقوط القسطنطينية (1453)", correctPosition: 4 }], difficulty: "hard" },
      { text: "رتب استقلال أمريكا اللاتينية:", orderItems: [{ id: "1", text: "حرب الاستقلال المكسيكية (1810)", correctPosition: 1 }, { id: "2", text: "استقلال الأرجنتين (1816)", correctPosition: 2 }, { id: "3", text: "استقلال البرازيل (1822)", correctPosition: 3 }, { id: "4", text: "معركة أياكوتشو (1824)", correctPosition: 4 }], difficulty: "hard" },
      { text: "رتب تأسيس الاتحاد السوفيتي:", orderItems: [{ id: "1", text: "تأسيس الاتحاد السوفيتي (1922)", correctPosition: 1 }, { id: "2", text: "خطة الخمس سنوات الأولى (1928)", correctPosition: 2 }, { id: "3", text: "التطهير الكبير (1936)", correctPosition: 3 }, { id: "4", text: "معركة موسكو (1941)", correctPosition: 4 }], difficulty: "hard" },
      { text: "رتب الفتوحات الإسلامية الأولى:", orderItems: [{ id: "1", text: "معركة أجنادين (634)", correctPosition: 1 }, { id: "2", text: "فتح دمشق (635)", correctPosition: 2 }, { id: "3", text: "معركة نهاوند (642)", correctPosition: 3 }, { id: "4", text: "الفتح الإسلامي لشمال إفريقيا (647)", correctPosition: 4 }], difficulty: "hard" },
      { text: "رتب الإصلاح البروتستانتي:", orderItems: [{ id: "1", text: "إصلاحات مارتن لوثر (1517)", correctPosition: 1 }, { id: "2", text: "مجمع ترنت (1545)", correctPosition: 2 }, { id: "3", text: "حرب الثلاثين عاماً (1618)", correctPosition: 3 }, { id: "4", text: "سلام وستفاليا (1648)", correctPosition: 4 }], difficulty: "hard" },
      { text: "رتب عصر المماليك:", orderItems: [{ id: "1", text: "عصر المماليك البحرية (1250)", correctPosition: 1 }, { id: "2", text: "معركة مرج دابق (1516)", correctPosition: 2 }, { id: "3", text: "فتح مصر العثماني (1517)", correctPosition: 3 }, { id: "4", text: "إلغاء الخلافة (1924)", correctPosition: 4 }], difficulty: "hard" },
      { text: "رتب عصر الاستكشاف:", orderItems: [{ id: "1", text: "اكتشاف أمريكا (1492)", correctPosition: 1 }, { id: "2", text: "معاهدة تورديسيلاس (1494)", correctPosition: 2 }, { id: "3", text: "غزو المكسيك (1519)", correctPosition: 3 }, { id: "4", text: "غزو بيرو (1532)", correctPosition: 4 }], difficulty: "medium" },
      { text: "رتب الجمهورية التركية:", orderItems: [{ id: "1", text: "معاهدة لوزان (1923)", correctPosition: 1 }, { id: "2", text: "إعلان الجمهورية التركية (1923)", correctPosition: 2 }, { id: "3", text: "إلغاء الخلافة (1924)", correctPosition: 3 }, { id: "4", text: "إصلاحات أتاتورك (1924-1938)", correctPosition: 4 }], difficulty: "hard" },
      { text: "رتب الإمبراطورية المغولية:", orderItems: [{ id: "1", text: "تأسيس الإمبراطورية المغولية (1206)", correctPosition: 1 }, { id: "2", text: "سقوط الخلافة العباسية (1258)", correctPosition: 2 }, { id: "3", text: "غزو الصين (1279)", correctPosition: 3 }, { id: "4", text: "وفاة تيمورلنك (1405)", correctPosition: 4 }], difficulty: "hard" },
      { text: "رتب الحروب البونية:", orderItems: [{ id: "1", text: "معركة كاناي (216 ق.م)", correctPosition: 1 }, { id: "2", text: "تدمير قرطاجة (146 ق.م)", correctPosition: 2 }, { id: "3", text: "معركة زاما (202 ق.م)", correctPosition: 3 }, { id: "4", text: "ثورة سبارتاكوس (73 ق.م)", correctPosition: 4 }], difficulty: "hard" },
      { text: "رتب الحرب الأهلية الأمريكية:", orderItems: [{ id: "1", text: "الحرب الأهلية (1861)", correctPosition: 1 }, { id: "2", text: "إلغاء العبودية (1865)", correctPosition: 2 }, { id: "3", text: "اغتيال لينكولن (1865)", correctPosition: 3 }, { id: "4", text: "إعادة الإعمار (1865-1877)", correctPosition: 4 }], difficulty: "medium" },
      { text: "رتب الثورات الروسية:", orderItems: [{ id: "1", text: "الحرب الروسية اليابانية (1904)", correctPosition: 1 }, { id: "2", text: "ثورة 1905", correctPosition: 2 }, { id: "3", text: "ثورة فبراير 1917", correctPosition: 3 }, { id: "4", text: "معاهدة بريست ليتوفسك (1918)", correctPosition: 4 }], difficulty: "hard" },
      { text: "رتب الثورة الصناعية:", orderItems: [{ id: "1", text: "حرب الأفيون الأولى (1839)", correctPosition: 1 }, { id: "2", text: "اختراع الباخرة البخارية (1807)", correctPosition: 2 }, { id: "3", text: "افتتاح قناة السويس (1869)", correctPosition: 3 }, { id: "4", text: "ثورة الملاكمين (1899)", correctPosition: 4 }], difficulty: "hard" },
      { text: "رتب توحيد إيطاليا:", orderItems: [{ id: "1", text: "استقلال اليونان (1830)", correctPosition: 1 }, { id: "2", text: "ثورة 1848", correctPosition: 2 }, { id: "3", text: "حرب القرم (1853)", correctPosition: 3 }, { id: "4", text: "توحيد إيطاليا (1861)", correctPosition: 4 }], difficulty: "hard" },
      { text: "رتب الحضارات اليونانية:", orderItems: [{ id: "1", text: "الحضارة المينوية (2700 ق.م)", correctPosition: 1 }, { id: "2", text: "الحضارة الميسينية (1600 ق.م)", correctPosition: 2 }, { id: "3", text: "العصر المظلم (1100 ق.م)", correctPosition: 3 }, { id: "4", text: "العصر الهلينستي (323 ق.م)", correctPosition: 4 }], difficulty: "hard" },
      { text: "رتب نابليون:", orderItems: [{ id: "1", text: "سقوط الباستيل (1789)", correctPosition: 1 }, { id: "2", text: "إعلان الإمبراطورية (1804)", correctPosition: 2 }, { id: "3", text: "معركة لايبزيغ (1813)", correctPosition: 3 }, { id: "4", text: "نفي نابليون إلى إلبا (1814)", correctPosition: 4 }], difficulty: "medium" },
    ].map(q => ({ text: q.text, subjectId, questionTypeId: 'order-challenge', orderItems: q.orderItems, difficulty: q.difficulty as 'easy' | 'medium' | 'hard', points: q.difficulty === 'easy' ? 10 : q.difficulty === 'medium' ? 15 : 20, timeLimit: 45 }));

    // More Who and Who Questions
    const whoAndWhoQuestions = [
      { text: "وصّل:", whoAndWhoData: { people: [{ id: "p1", name: "تشارلز داروين" }, { id: "p2", name: "غريغور مندل" }], achievements: [{ id: "a1", text: "نظرية التطور", personId: "p1" }, { id: "a2", text: "أساس علم الوراثة", personId: "p2" }] }, difficulty: "medium" },
      { text: "وصّل:", whoAndWhoData: { people: [{ id: "p1", name: "الأخوان رايت" }, { id: "p2", name: "كارل بنز" }], achievements: [{ id: "a1", text: "اخترعوا الطائرة", personId: "p1" }, { id: "a2", text: "صنع أول سيارة بنزين", personId: "p2" }] }, difficulty: "easy" },
      { text: "وصّل:", whoAndWhoData: { people: [{ id: "p1", name: "ألكسندر غراهام بيل" }, { id: "p2", name: "غولييلمو ماركوني" }], achievements: [{ id: "a1", text: "اخترع التليفون", personId: "p1" }, { id: "a2", text: "اخترع الراديو", personId: "p2" }] }, difficulty: "medium" },
      { text: "وصّل:", whoAndWhoData: { people: [{ id: "p1", name: "ألكسندر فليمنغ" }, { id: "p2", name: "إدوارد جينر" }], achievements: [{ id: "a1", text: "اكتشف البنسلين", personId: "p1" }, { id: "a2", text: "اخترع اللقاح", personId: "p2" }] }, difficulty: "medium" },
      { text: "وصّل:", whoAndWhoData: { people: [{ id: "p1", name: "يوهانس غوتنبرغ" }, { id: "p2", name: "تيم بيرنرز لي" }], achievements: [{ id: "a1", text: "اخترع الطباعة", personId: "p1" }, { id: "a2", text: "اخترع الإنترنت", personId: "p2" }] }, difficulty: "medium" },
      { text: "وصّل:", whoAndWhoData: { people: [{ id: "p1", name: "أوغسطس قيصر" }, { id: "p2", name: "الإمبراطور فسباسيان" }], achievements: [{ id: "a1", text: "أسس الإمبراطورية الرومانية", personId: "p1" }, { id: "a2", text: "بنى الكولوسيوم", personId: "p2" }] }, difficulty: "hard" },
      { text: "وصّل:", whoAndWhoData: { people: [{ id: "p1", name: "بنيامين فرانكلين" }, { id: "p2", name: "جيمس واط" }], achievements: [{ id: "a1", text: "اكتشف الكهرباء", personId: "p1" }, { id: "a2", text: "اخترع المحرك البخاري", personId: "p2" }] }, difficulty: "medium" },
      { text: "وصّل:", whoAndWhoData: { people: [{ id: "p1", name: "توسان لوفيرتور" }, { id: "p2", name: "جان جاك ديسالين" }], achievements: [{ id: "a1", text: "قاد ثورة هايتي", personId: "p1" }, { id: "a2", text: "أعلن استقلال هايتي", personId: "p2" }] }, difficulty: "hard" },
      { text: "وصّل:", whoAndWhoData: { people: [{ id: "p1", name: "جون لوجي بيرد" }, { id: "p2", name: "ستيف جوبز" }], achievements: [{ id: "a1", text: "اخترع التلفزيون", personId: "p1" }, { id: "a2", text: "أسس شركة أبل", personId: "p2" }] }, difficulty: "medium" },
      { text: "وصّل:", whoAndWhoData: { people: [{ id: "p1", name: "نابليون بونابرت" }, { id: "p2", name: "دوق ولينغتون" }], achievements: [{ id: "a1", text: "قاد معركة واترلو", personId: "p1" }, { id: "a2", text: "هزم نابليون", personId: "p2" }] }, difficulty: "medium" },
      { text: "وصّل:", whoAndWhoData: { people: [{ id: "p1", name: "فرانكلين روزفلت" }, { id: "p2", name: "إليانور روزفلت" }], achievements: [{ id: "a1", text: "أسس الأمم المتحدة", personId: "p1" }, { id: "a2", text: "صاغت إعلان حقوق الإنسان", personId: "p2" }] }, difficulty: "hard" },
      { text: "وصّل:", whoAndWhoData: { people: [{ id: "p1", name: "توماس دافنبورت" }, { id: "p2", name: "هنري فورد" }], achievements: [{ id: "a1", text: "اخترع السيارة الكهربائية", personId: "p1" }, { id: "a2", text: "طور خط التجميع", personId: "p2" }] }, difficulty: "hard" },
      { text: "وصّل:", whoAndWhoData: { people: [{ id: "p1", name: "باتشاكوتي" }, { id: "p2", name: "فرانسيسكو بيزارو" }], achievements: [{ id: "a1", text: "أسس إمبراطورية الإنكا", personId: "p1" }, { id: "a2", text: "دمر إمبراطورية الإنكا", personId: "p2" }] }, difficulty: "hard" },
      { text: "وصّل:", whoAndWhoData: { people: [{ id: "p1", name: "جيمس كوك" }, { id: "p2", name: "ماثيو فليندرز" }], achievements: [{ id: "a1", text: "اكتشف أستراليا", personId: "p1" }, { id: "a2", text: "رسم خريطتها بدقة", personId: "p2" }] }, difficulty: "hard" },
      { text: "وصّل:", whoAndWhoData: { people: [{ id: "p1", name: "لازلو بيرو" }, { id: "p2", name: "نيكولا كونتي" }], achievements: [{ id: "a1", text: "اخترع القلم الحبر", personId: "p1" }, { id: "a2", text: "اخترع القلم الرصاص", personId: "p2" }] }, difficulty: "hard" },
      { text: "وصّل:", whoAndWhoData: { people: [{ id: "p1", name: "جيمس هوبان" }, { id: "p2", name: "جورج واشنطن" }], achievements: [{ id: "a1", text: "بنى البيت الأبيض", personId: "p1" }, { id: "a2", text: "أول رئيس سكنه", personId: "p2" }] }, difficulty: "hard" },
      { text: "وصّل:", whoAndWhoData: { people: [{ id: "p1", name: "روبرت واتسون وات" }, { id: "p2", name: "بول لانجفان" }], achievements: [{ id: "a1", text: "اخترع الرادار", personId: "p1" }, { id: "a2", text: "اخترع السونار", personId: "p2" }] }, difficulty: "hard" },
      { text: "وصّل:", whoAndWhoData: { people: [{ id: "p1", name: "هيتور دا سيلفا كوستا" }, { id: "p2", name: "بول لاندوفسكي" }], achievements: [{ id: "a1", text: "بنى تمثال المسيح الفادي", personId: "p1" }, { id: "a2", text: "صممه", personId: "p2" }] }, difficulty: "hard" },
      { text: "وصّل:", whoAndWhoData: { people: [{ id: "p1", name: "ديفيد بن غوريون" }, { id: "p2", name: "مناحم بيغن" }], achievements: [{ id: "a1", text: "أسس دولة إسرائيل", personId: "p1" }, { id: "a2", text: "وقع اتفاقيات كامب ديفيد", personId: "p2" }] }, difficulty: "medium" },
      { text: "وصّل:", whoAndWhoData: { people: [{ id: "p1", name: "جاكوب بيركنز" }, { id: "p2", name: "ويليس كاريير" }], achievements: [{ id: "a1", text: "اخترع الثلاجة", personId: "p1" }, { id: "a2", text: "اخترع المكيف", personId: "p2" }] }, difficulty: "hard" },
    ].map(q => ({ text: q.text, subjectId, questionTypeId: 'who-and-who', whoAndWhoData: q.whoAndWhoData, difficulty: q.difficulty as 'easy' | 'medium' | 'hard', points: q.difficulty === 'easy' ? 10 : q.difficulty === 'medium' ? 15 : 20, timeLimit: 50 }));

    const allQuestions = [...fourOptionsQuestions, ...orderQuestions, ...whoAndWhoQuestions];
    await Question.insertMany(allQuestions);

    console.log(`✅ تم إضافة ${allQuestions.length} سؤال تاريخي إضافي!`);
    console.log(`   - ${fourOptionsQuestions.length} أسئلة اختيار من 4`);
    console.log(`   - ${orderQuestions.length} أسئلة ترتيب`);
    console.log(`   - ${whoAndWhoQuestions.length} أسئلة من ومن`);
    
    process.exit(0);
  } catch (error) {
    console.error('❌ خطأ:', error);
    process.exit(1);
  }
};

seedHistoryPart2();

