import dotenv from 'dotenv';
import { connectDatabase } from '../config/database.js';
import Subject from '../models/Subject.js';
import Question from '../models/Question.js';

dotenv.config();

const seedGeographyFourOptions = async () => {
  try {
    await connectDatabase();

    // Find or create Geography subject
    let geographySubject = await Subject.findOne({ name: 'Geography' });
    if (!geographySubject) {
      geographySubject = await Subject.create({
        name: 'Geography',
        nameAr: 'الجغرافيا',
        description: 'أسئلة جغرافية',
        color: '#10b981'
      });
    }
    const subjectId = geographySubject._id;

    console.log('🌱 Adding Geography Four Options Questions...');

    // All 50 geography four-options questions
    const questionsData = [
      { text: "ما هي الظاهرة التي تسببها قوة كوريوليس؟", options: [{ id: "1", text: "المد والجزر", isCorrect: false }, { id: "2", text: "تغير فصول السنة", isCorrect: false }, { id: "3", text: "انحراف الرياح والتيارات المحيطية", isCorrect: true }, { id: "4", text: "الزلازل", isCorrect: false }], difficulty: "medium" },
      { text: "أي من البحار التالية يعتبر بحراً داخلياً مغلقاً ولا يتصل بأي محيط؟", options: [{ id: "1", text: "البحر الأسود", isCorrect: false }, { id: "2", text: "البحر الأحمر", isCorrect: false }, { id: "3", text: "بحر قزوين", isCorrect: true }, { id: "4", text: "بحر البلطيق", isCorrect: false }], difficulty: "easy" },
      { text: "ما هو الاسم الجغرافي لأكبر حوض تصريف نهري في العالم؟", options: [{ id: "1", text: "حوض نهر الكونغو", isCorrect: false }, { id: "2", text: "حوض نهر المسيسيبي", isCorrect: false }, { id: "3", text: "حوض نهر الأمازون", isCorrect: true }, { id: "4", text: "حوض نهر النيل", isCorrect: false }], difficulty: "medium" },
      { text: "ما هي القارة الوحيدة التي يمر بها خطوط الطول والعرض الأربعة الرئيسية (الاستواء، غرينتش، السرطان، الجدي)؟", options: [{ id: "1", text: "آسيا", isCorrect: false }, { id: "2", text: "أوروبا", isCorrect: false }, { id: "3", text: "أفريقيا", isCorrect: true }, { id: "4", text: "أمريكا الجنوبية", isCorrect: false }], difficulty: "hard" },
      { text: "ما هي العملية الجيولوجية التي تؤدي إلى تشكل الكهوف في الصخور الجيرية؟", options: [{ id: "1", text: "التعرية الريحية", isCorrect: false }, { id: "2", text: "الحت الجليدي", isCorrect: false }, { id: "3", text: "الإذابة الكيميائية (كارست)", isCorrect: true }, { id: "4", text: "الترسيب النهري", isCorrect: false }], difficulty: "medium" },
      { text: "ما هو المضيق الذي يربط بين المحيط الأطلسي والبحر الأبيض المتوسط؟", options: [{ id: "1", text: "مضيق باب المندب", isCorrect: false }, { id: "2", text: "مضيق هرمز", isCorrect: false }, { id: "3", text: "مضيق جبل طارق", isCorrect: true }, { id: "4", text: "مضيق الدردنيل", isCorrect: false }], difficulty: "easy" },
      { text: "أي من هذه الدول تقع في قارتين مختلفتين؟", options: [{ id: "1", text: "الصين", isCorrect: false }, { id: "2", text: "تركيا", isCorrect: true }, { id: "3", text: "تشيلي", isCorrect: false }, { id: "4", text: "المغرب", isCorrect: false }], difficulty: "medium" },
      { text: "ما هو المصطلح الذي يصف انحدار الكثافة السكانية مع الابتعاد عن مركز المدينة؟", options: [{ id: "1", text: "الانتشار العمراني", isCorrect: false }, { id: "2", text: "المركزية", isCorrect: false }, { id: "3", text: "تدرج الكثافة", isCorrect: true }, { id: "4", text: "التوزيع العنقودي", isCorrect: false }], difficulty: "hard" },
      { text: "ما هي القوة الرئيسية المسؤولة عن تآكل الجرف الصخري البحري؟", options: [{ id: "1", text: "التعرية الجليدية", isCorrect: false }, { id: "2", text: "الأمطار الحمضية", isCorrect: false }, { id: "3", text: "الأمواج والتيارات البحرية", isCorrect: true }, { id: "4", text: "التعرية الريحية", isCorrect: false }], difficulty: "medium" },
      { text: "ما هي الدولة التي تمتلك أكبر عدد من الجزر في العالم؟", options: [{ id: "1", text: "اليونان", isCorrect: false }, { id: "2", text: "إندونيسيا", isCorrect: false }, { id: "3", text: "السويد", isCorrect: true }, { id: "4", text: "الفلبين", isCorrect: false }], difficulty: "hard" },
      { text: "أي من الدول التالية لا يطل على المحيط الأطلسي؟", options: [{ id: "1", text: "المغرب", isCorrect: false }, { id: "2", text: "البرازيل", isCorrect: false }, { id: "3", text: "نيجيريا", isCorrect: false }, { id: "4", text: "باكستان", isCorrect: true }], difficulty: "easy" },
      { text: "ما هو الاسم العلمي للعملية التي يتحول فيها الجليد مباشرة إلى بخار دون المرور بالحالة السائلة؟", options: [{ id: "1", text: "التكاثف", isCorrect: false }, { id: "2", text: "التبخر", isCorrect: false }, { id: "3", text: "التسامي", isCorrect: true }, { id: "4", text: "الانصهار", isCorrect: false }], difficulty: "medium" },
      { text: "تسمى المناطق التي تشهد تصادماً بين الصفائح التكتونية بحدود الصفائح:", options: [{ id: "1", text: "المتباعدة", isCorrect: false }, { id: "2", text: "المتقاربة", isCorrect: true }, { id: "3", text: "المتحولة", isCorrect: false }, { id: "4", text: "الهامشية", isCorrect: false }], difficulty: "hard" },
      { text: "أي من هذه الأقاليم المناخية يتميز بالصيف الحار الجاف والشتاء المعتدل الممطر؟", options: [{ id: "1", text: "الاستوائي", isCorrect: false }, { id: "2", text: "المداري الموسمي", isCorrect: false }, { id: "3", text: "البحر الأبيض المتوسط", isCorrect: true }, { id: "4", text: "القطبي", isCorrect: false }], difficulty: "easy" },
      { text: "ما هو المصطلح الجغرافي للخط الذي يفصل بين المناطق التي تستقبل ضوء الشمس وتلك التي لا تستقبله؟", options: [{ id: "1", text: "دائرة العرض", isCorrect: false }, { id: "2", text: "خط الزوال", isCorrect: false }, { id: "3", text: "دائرة الإضاءة (دائرة النهار والليل)", isCorrect: true }, { id: "4", text: "خط الأفق", isCorrect: false }], difficulty: "medium" },
      { text: "أي من الظواهر التالية هو المسؤول عن تشكل الأودية المعلقة (Hanging Valleys)؟", options: [{ id: "1", text: "النشاط البركاني", isCorrect: false }, { id: "2", text: "التعرية النهرية", isCorrect: false }, { id: "3", text: "التعرية الجليدية", isCorrect: true }, { id: "4", text: "حركات المد والجزر", isCorrect: false }], difficulty: "hard" },
      { text: "ما هي أكبر بحيرة مالحة في العالم من حيث الحجم؟", options: [{ id: "1", text: "البحر الميت", isCorrect: false }, { id: "2", text: "البحر الأسود", isCorrect: false }, { id: "3", text: "بحر قزوين", isCorrect: true }, { id: "4", text: "البحيرة المالحة الكبرى", isCorrect: false }], difficulty: "easy" },
      { text: "تسمى حركة السكان من الريف إلى المدن بـ:", options: [{ id: "1", text: "الهجرة الخارجية", isCorrect: false }, { id: "2", text: "التحضر", isCorrect: true }, { id: "3", text: "التصحر", isCorrect: false }, { id: "4", text: "الانتشار", isCorrect: false }], difficulty: "medium" },
      { text: "ما هي السلسلة الجبلية التي تفصل بين أوروبا وآسيا؟", options: [{ id: "1", text: "جبال الألب", isCorrect: false }, { id: "2", text: "جبال الهملايا", isCorrect: false }, { id: "3", text: "جبال الأورال", isCorrect: true }, { id: "4", text: "جبال روكي", isCorrect: false }], difficulty: "easy" },
      { text: "أي طبقة من الغلاف الجوي تحدث فيها معظم الظواهر الجوية كالأمطار والرياح؟", options: [{ id: "1", text: "الستراتوسفير", isCorrect: false }, { id: "2", text: "الميزوسفير", isCorrect: false }, { id: "3", text: "التروبوسفير", isCorrect: true }, { id: "4", text: "الثيرموسفير", isCorrect: false }], difficulty: "medium" },
      { text: "أي من الدول التالية تعد إقليماً داخلياً (Landlocked)؟", options: [{ id: "1", text: "أثيوبيا", isCorrect: true }, { id: "2", text: "كينيا", isCorrect: false }, { id: "3", text: "مصر", isCorrect: false }, { id: "4", text: "الجزائر", isCorrect: false }], difficulty: "medium" },
      { text: "ما هو العامل الأساسي في تحديد التوزيع الأفقي والعمودي للمناخ؟", options: [{ id: "1", text: "توزيع اليابسة والماء", isCorrect: false }, { id: "2", text: "التضاريس", isCorrect: false }, { id: "3", text: "خطوط العرض (الموقع بالنسبة لخط الاستواء)", isCorrect: true }, { id: "4", text: "التيارات البحرية", isCorrect: false }], difficulty: "hard" },
      { text: "ما هي أصغر دولة في العالم من حيث المساحة؟", options: [{ id: "1", text: "موناكو", isCorrect: false }, { id: "2", text: "الفاتيكان", isCorrect: true }, { id: "3", text: "ناورو", isCorrect: false }, { id: "4", text: "سان مارينو", isCorrect: false }], difficulty: "easy" },
      { text: "المنطقة التي تفصل بين السهول الغابوية والسافانا في إفريقيا تسمى:", options: [{ id: "1", text: "السهول الكبرى", isCorrect: false }, { id: "2", text: "الدائرة القطبية", isCorrect: false }, { id: "3", text: "الساحل", isCorrect: true }, { id: "4", text: "التندرا", isCorrect: false }], difficulty: "hard" },
      { text: "أين تقع صحراء أتاكاما، التي تعد أكثر المناطق جفافاً في العالم؟", options: [{ id: "1", text: "أستراليا", isCorrect: false }, { id: "2", text: "شمال أفريقيا", isCorrect: false }, { id: "3", text: "أمريكا الجنوبية", isCorrect: true }, { id: "4", text: "آسيا الوسطى", isCorrect: false }], difficulty: "medium" },
      { text: "أي من الموارد التالية يعتبر مورداً غير متجدد؟", options: [{ id: "1", text: "الطاقة الشمسية", isCorrect: false }, { id: "2", text: "الرياح", isCorrect: false }, { id: "3", text: "الفحم الحجري", isCorrect: true }, { id: "4", text: "المياه الجارية", isCorrect: false }], difficulty: "easy" },
      { text: "ما هي التيارات البحرية التي تنقل المياه الدافئة من المناطق الاستوائية إلى القطبين؟", options: [{ id: "1", text: "التيارات السطحية الباردة", isCorrect: false }, { id: "2", text: "التيارات الدافئة", isCorrect: true }, { id: "3", text: "التيارات القطبية", isCorrect: false }, { id: "4", text: "تيارات القاع", isCorrect: false }], difficulty: "medium" },
      { text: "ما هو الاسم الجغرافي للهضبة الشاسعة الواقعة في جنوب آسيا؟", options: [{ id: "1", text: "هضبة التبت", isCorrect: false }, { id: "2", text: "هضبة الدكن", isCorrect: true }, { id: "3", text: "هضبة الأناضول", isCorrect: false }, { id: "4", text: "هضبة كولومبيا", isCorrect: false }], difficulty: "hard" },
      { text: "الخط الفاصل بين كندا والولايات المتحدة الأمريكية (عدا ألاسكا) هو:", options: [{ id: "1", text: "دائرة عرض 45 شمالاً", isCorrect: false }, { id: "2", text: "دائرة عرض 49 شمالاً", isCorrect: true }, { id: "3", text: "خط الطول 100 غرباً", isCorrect: false }, { id: "4", text: "الخط الدولي للتاريخ", isCorrect: false }], difficulty: "hard" },
      { text: "أين يقع نهر الفولغا، أطول نهر في أوروبا؟", options: [{ id: "1", text: "ألمانيا", isCorrect: false }, { id: "2", text: "روسيا", isCorrect: true }, { id: "3", text: "فرنسا", isCorrect: false }, { id: "4", text: "أوكرانيا", isCorrect: false }], difficulty: "easy" },
      { text: "ما هي أكبر منطقة زمنية في العالم؟", options: [{ id: "1", text: "الصين", isCorrect: false }, { id: "2", text: "روسيا", isCorrect: true }, { id: "3", text: "الولايات المتحدة الأمريكية", isCorrect: false }, { id: "4", text: "كندا", isCorrect: false }], difficulty: "medium" },
      { text: "أي نوع من البراكين يتميز بانفجارات عنيفة وتشكل قبة بركانية حادة؟", options: [{ id: "1", text: "بركان درعي", isCorrect: false }, { id: "2", text: "بركان مركب (طبقي)", isCorrect: true }, { id: "3", text: "بركان مخروطي", isCorrect: false }, { id: "4", text: "بركان شقي", isCorrect: false }], difficulty: "hard" },
      { text: "التيار البارد الذي يمر قبالة الساحل الغربي لأمريكا الجنوبية هو:", options: [{ id: "1", text: "تيار الخليج", isCorrect: false }, { id: "2", text: "تيار كناري", isCorrect: false }, { id: "3", text: "تيار بيرو (هومبولت)", isCorrect: true }, { id: "4", text: "تيار كوروشيو", isCorrect: false }], difficulty: "medium" },
      { text: "ما هي الظاهرة الجغرافية التي تنتج عن هبوب رياح جافة ودافئة على المنحدرات الجبلية بعد أن تفقد رطوبتها في الجانب الآخر؟", options: [{ id: "1", text: "تأثير الظل المطري", isCorrect: true }, { id: "2", text: "الإعصار المداري", isCorrect: false }, { id: "3", text: "الضباب الدخاني", isCorrect: false }, { id: "4", text: "الندى", isCorrect: false }], difficulty: "hard" },
      { text: "أي من الدول التالية لا تمتلك حدوداً برية مع ألمانيا؟", options: [{ id: "1", text: "بولندا", isCorrect: false }, { id: "2", text: "فرنسا", isCorrect: false }, { id: "3", text: "إيطاليا", isCorrect: true }, { id: "4", text: "الدنمارك", isCorrect: false }], difficulty: "medium" },
      { text: "السهول العشبية الواسعة في أمريكا الشمالية تسمى:", options: [{ id: "1", text: "التايغا", isCorrect: false }, { id: "2", text: "السافانا", isCorrect: false }, { id: "3", text: "البراري (البريريز)", isCorrect: true }, { id: "4", text: "البامباس", isCorrect: false }], difficulty: "easy" },
      { text: "ما هو الاسم الجغرافي للكتلة الأرضية الأصلية التي تكونت قبل حوالي 300 مليون سنة؟", options: [{ id: "1", text: "لوراسيا", isCorrect: false }, { id: "2", text: "جوندوانا", isCorrect: false }, { id: "3", text: "بانجيا", isCorrect: true }, { id: "4", text: "تيثيس", isCorrect: false }], difficulty: "medium" },
      { text: "ما هي القناة التي تربط البحر الأحمر بالبحر الأبيض المتوسط؟", options: [{ id: "1", text: "قناة بنما", isCorrect: false }, { id: "2", text: "قناة السويس", isCorrect: true }, { id: "3", text: "قناة كييل", isCorrect: false }, { id: "4", text: "مضيق ملقا", isCorrect: false }], difficulty: "easy" },
      { text: "تسمى الصخور التي تعرضت لضغط وحرارة عالية فتحولت إلى شكل جديد بـ:", options: [{ id: "1", text: "صخور نارية", isCorrect: false }, { id: "2", text: "صخور متحولة", isCorrect: true }, { id: "3", text: "صخور رسوبية", isCorrect: false }, { id: "4", text: "صخور بركانية", isCorrect: false }], difficulty: "medium" },
      { text: "الخط الزمني الدولي (International Date Line) يتبع تقريباً خط الطول:", options: [{ id: "1", text: "صفر", isCorrect: false }, { id: "2", text: "90 درجة شرقاً", isCorrect: false }, { id: "3", text: "180 درجة", isCorrect: true }, { id: "4", text: "90 درجة غرباً", isCorrect: false }], difficulty: "easy" },
      { text: "أي من القمم الجبلية التالية لا تقع ضمن سلسلة جبال روكي؟", options: [{ id: "1", text: "جبل إلبروس", isCorrect: true }, { id: "2", text: "جبل ماونت بروس", isCorrect: false }, { id: "3", text: "جبل إلبرت", isCorrect: false }, { id: "4", text: "جبل فورت", isCorrect: false }], difficulty: "hard" },
      { text: "ما هي الدولة التي تحدها كل من الصين وروسيا؟", options: [{ id: "1", text: "كازاخستان", isCorrect: false }, { id: "2", text: "كوريا الشمالية", isCorrect: false }, { id: "3", text: "منغوليا", isCorrect: true }, { id: "4", text: "الهند", isCorrect: false }], difficulty: "medium" },
      { text: "ما هو الاسم الجغرافي للتيار الهوائي السريع الذي يدور حول الأرض على ارتفاعات عالية؟", options: [{ id: "1", text: "رياح التجارة", isCorrect: false }, { id: "2", text: "التيار النفاث (Jet Stream)", isCorrect: true }, { id: "3", text: "رياح الغرب العكسية", isCorrect: false }, { id: "4", text: "رياح كوريوليس", isCorrect: false }], difficulty: "hard" },
      { text: "الجزيرة التي تقسمها الحدود بين دولتين مختلفتين هي:", options: [{ id: "1", text: "هاواي", isCorrect: false }, { id: "2", text: "مدغشقر", isCorrect: false }, { id: "3", text: "هيسبانيولا", isCorrect: true }, { id: "4", text: "صقلية", isCorrect: false }], difficulty: "medium" },
      { text: "ما هو المضيق الذي يفصل بين أوروبا وأفريقيا عند مدخل البحر الأحمر؟", options: [{ id: "1", text: "مضيق جبل طارق", isCorrect: false }, { id: "2", text: "مضيق باب المندب", isCorrect: true }, { id: "3", text: "مضيق هرمز", isCorrect: false }, { id: "4", text: "مضيق البوسفور", isCorrect: false }], difficulty: "easy" },
      { text: "أي نوع من الغابات يتميز بتساقط أوراقه موسمياً؟", options: [{ id: "1", text: "الغابات الاستوائية المطيرة", isCorrect: false }, { id: "2", text: "غابات البحر المتوسط", isCorrect: false }, { id: "3", text: "الغابات النفضية المعتدلة", isCorrect: true }, { id: "4", text: "غابات الصنوبر القطبية", isCorrect: false }], difficulty: "medium" },
      { text: "ما هي القارة التي تضم أكبر عدد من الدول الداخلية (غير الساحلية)؟", options: [{ id: "1", text: "آسيا", isCorrect: false }, { id: "2", text: "أوروبا", isCorrect: false }, { id: "3", text: "أفريقيا", isCorrect: true }, { id: "4", text: "أمريكا الجنوبية", isCorrect: false }], difficulty: "hard" },
      { text: "ما هو الاسم الجغرافي للمياه التي تقع بين الجزر الساحلية والبر الرئيسي؟", options: [{ id: "1", text: "الخندق البحري", isCorrect: false }, { id: "2", text: "البحر الإقليمي", isCorrect: false }, { id: "3", text: "اللاغون (البحيرة الشاطئية)", isCorrect: true }, { id: "4", text: "التيار السطحي", isCorrect: false }], difficulty: "hard" },
      { text: "ما هي المدينة التي تقع على خط التقسيم القاري (Continental Divide) في أمريكا الشمالية؟", options: [{ id: "1", text: "لوس أنجلوس", isCorrect: false }, { id: "2", text: "دنفر", isCorrect: true }, { id: "3", text: "شيكاغو", isCorrect: false }, { id: "4", text: "نيويورك", isCorrect: false }], difficulty: "hard" },
      { text: "ما هو أعلى جبل في أفريقيا؟", options: [{ id: "1", text: "جبل كينيا", isCorrect: false }, { id: "2", text: "جبل كلمنجارو", isCorrect: true }, { id: "3", text: "جبل طوبقال", isCorrect: false }, { id: "4", text: "جبل أطلس", isCorrect: false }], difficulty: "easy" },
      { text: "أي من الأنهار التالية لا يصب في المحيط الأطلسي؟", options: [{ id: "1", text: "نهر الأمازون", isCorrect: false }, { id: "2", text: "نهر الكونغو", isCorrect: false }, { id: "3", text: "نهر اليانغتسي", isCorrect: true }, { id: "4", text: "نهر المسيسيبي", isCorrect: false }], difficulty: "medium" },
      { text: "ما هي الصخور التي تتكون من بقايا الكائنات الحية (مثل المرجان والمحار)؟", options: [{ id: "1", text: "صخور الرخام المتحولة", isCorrect: false }, { id: "2", text: "صخور الحجر الجيري الرسوبية", isCorrect: true }, { id: "3", text: "صخور البازلت النارية", isCorrect: false }, { id: "4", text: "صخور الكوارتزيت المتحولة", isCorrect: false }], difficulty: "hard" },
      { text: "تسمى السهول العشبية الواسعة في أمريكا الجنوبية بـ:", options: [{ id: "1", text: "البراري", isCorrect: false }, { id: "2", text: "السافانا", isCorrect: false }, { id: "3", text: "البامباس", isCorrect: true }, { id: "4", text: "التندرا", isCorrect: false }], difficulty: "medium" },
      { text: "أي من الدول التالية ليس لديها حدود مع البحر الأسود؟", options: [{ id: "1", text: "بلغاريا", isCorrect: false }, { id: "2", text: "اليونان", isCorrect: true }, { id: "3", text: "رومانيا", isCorrect: false }, { id: "4", text: "تركيا", isCorrect: false }], difficulty: "medium" },
      { text: "ما هو أطول نهر في قارة آسيا؟", options: [{ id: "1", text: "نهر الغانج", isCorrect: false }, { id: "2", text: "نهر اليانغتسي", isCorrect: true }, { id: "3", text: "نهر ميكونغ", isCorrect: false }, { id: "4", text: "نهر هوانغ هي", isCorrect: false }], difficulty: "easy" },
      { text: "أي قارة لديها أعلى متوسط ارتفاع؟", options: [{ id: "1", text: "أفريقيا", isCorrect: false }, { id: "2", text: "أمريكا الشمالية", isCorrect: false }, { id: "3", text: "أنتاركتيكا", isCorrect: true }, { id: "4", text: "أستراليا", isCorrect: false }], difficulty: "hard" },
      { text: "ما هي المادة التي تتركز في طبقة الأوزون وتحمي الأرض من الأشعة فوق البنفسجية؟", options: [{ id: "1", text: "ثاني أكسيد الكربون", isCorrect: false }, { id: "2", text: "الميثان", isCorrect: false }, { id: "3", text: "الأكسجين الثلاثي (الأوزون)", isCorrect: true }, { id: "4", text: "بخار الماء", isCorrect: false }], difficulty: "easy" },
      { text: "العملية التي يتم فيها نقل المواد المفتتة والمنحلة بفعل الرياح والمياه والجليد تسمى:", options: [{ id: "1", text: "التجوية", isCorrect: false }, { id: "2", text: "الترسيب", isCorrect: false }, { id: "3", text: "التعرية", isCorrect: true }, { id: "4", text: "التكتونيات", isCorrect: false }], difficulty: "medium" },
      { text: "ما هو الاسم الجغرافي للغطاء النباتي الذي ينمو على التربة المتجمدة في المنطقة القطبية الشمالية؟", options: [{ id: "1", text: "التايغا", isCorrect: false }, { id: "2", text: "التندرا", isCorrect: true }, { id: "3", text: "البراري", isCorrect: false }, { id: "4", text: "السافانا", isCorrect: false }], difficulty: "medium" },
      { text: "ما هي المدينة التي تقع على التقاء نهرين رئيسيين هما النيل الأبيض والنيل الأزرق؟", options: [{ id: "1", text: "القاهرة", isCorrect: false }, { id: "2", text: "الخرطوم", isCorrect: true }, { id: "3", text: "الأقصر", isCorrect: false }, { id: "4", text: "أسوان", isCorrect: false }], difficulty: "easy" },
      { text: "أي من خطوط العرض التالية هو مدار الجدي؟", options: [{ id: "1", text: "23.5° شمالاً", isCorrect: false }, { id: "2", text: "23.5° جنوباً", isCorrect: true }, { id: "3", text: "66.5° شمالاً", isCorrect: false }, { id: "4", text: "66.5° جنوباً", isCorrect: false }], difficulty: "medium" },
      { text: "المدينة التي تقع في أقصى جنوب العالم هي:", options: [{ id: "1", text: "ويلينغتون", isCorrect: false }, { id: "2", text: "أوشوايا", isCorrect: true }, { id: "3", text: "بونتا أريناس", isCorrect: false }, { id: "4", text: "كيب تاون", isCorrect: false }], difficulty: "hard" },
      { text: "ما هي الظاهرة التي تحدث عندما تغوص صفيحة تكتونية تحت صفيحة أخرى؟", options: [{ id: "1", text: "الامتداد القاري", isCorrect: false }, { id: "2", text: "الانصهار", isCorrect: false }, { id: "3", text: "الاندساس", isCorrect: true }, { id: "4", text: "التصادم", isCorrect: false }], difficulty: "hard" },
      { text: "تسمى المناطق التي تكون فيها درجات الحرارة والضغط متماثلة بـ:", options: [{ id: "1", text: "مناطق التساوي الحراري", isCorrect: false }, { id: "2", text: "كتل الهواء", isCorrect: true }, { id: "3", text: "الأقاليم المناخية", isCorrect: false }, { id: "4", text: "الحدود الجوية", isCorrect: false }], difficulty: "medium" },
      { text: "ما هي الدولة التي تعتبر موطناً لأكبر غابة مطيرة في العالم؟", options: [{ id: "1", text: "إندونيسيا", isCorrect: false }, { id: "2", text: "الكونغو", isCorrect: false }, { id: "3", text: "البرازيل", isCorrect: true }, { id: "4", text: "الهند", isCorrect: false }], difficulty: "easy" },
      { text: "أين يقع وادي الموت (Death Valley)، وهو أدنى نقطة في أمريكا الشمالية؟", options: [{ id: "1", text: "كندا", isCorrect: false }, { id: "2", text: "المكسيك", isCorrect: false }, { id: "3", text: "الولايات المتحدة الأمريكية", isCorrect: true }, { id: "4", text: "غرينلاند", isCorrect: false }], difficulty: "medium" },
      { text: "ما هو المضيق الذي يقع بين شبه الجزيرة العربية والقرن الأفريقي؟", options: [{ id: "1", text: "مضيق جبل طارق", isCorrect: false }, { id: "2", text: "مضيق هرمز", isCorrect: false }, { id: "3", text: "مضيق باب المندب", isCorrect: true }, { id: "4", text: "مضيق ملقا", isCorrect: false }], difficulty: "easy" },
      { text: "ما هو الاسم الذي يطلق على الخط الذي يربط بين المناطق ذات درجة الحرارة المتساوية على الخريطة؟", options: [{ id: "1", text: "خطوط تساوي الضغط", isCorrect: false }, { id: "2", text: "خطوط تساوي الارتفاع", isCorrect: false }, { id: "3", text: "خطوط تساوي الحرارة (الايزوثيرم)", isCorrect: true }, { id: "4", text: "خطوط تساوي المطر", isCorrect: false }], difficulty: "medium" },
      { text: "تعتبر جبال الألب من أنواع الجبال:", options: [{ id: "1", text: "البلوكية (الصدعية)", isCorrect: false }, { id: "2", text: "المطوية (الثني)", isCorrect: true }, { id: "3", text: "البركانية", isCorrect: false }, { id: "4", text: "القببية", isCorrect: false }], difficulty: "hard" },
      { text: "التيار البارد الذي يساهم في جعل صحراء أتاكاما جافة جداً هو:", options: [{ id: "1", text: "تيار البرازيل", isCorrect: false }, { id: "2", text: "تيار هومبولت (بيرو)", isCorrect: true }, { id: "3", text: "تيار ألاسكا", isCorrect: false }, { id: "4", text: "تيار لاباردور", isCorrect: false }], difficulty: "medium" },
      { text: "ما هي القارة التي تعد 'قارة الثلج الأبدي'؟", options: [{ id: "1", text: "أوروبا", isCorrect: false }, { id: "2", text: "آسيا", isCorrect: false }, { id: "3", text: "أنتاركتيكا", isCorrect: true }, { id: "4", text: "أمريكا الشمالية", isCorrect: false }], difficulty: "easy" },
      { text: "أين تقع بحيرة فكتوريا، ثاني أكبر بحيرة عذبة في العالم؟", options: [{ id: "1", text: "أمريكا الشمالية", isCorrect: false }, { id: "2", text: "أفريقيا", isCorrect: true }, { id: "3", text: "آسيا", isCorrect: false }, { id: "4", text: "أوروبا", isCorrect: false }], difficulty: "medium" }
    ];

    // Prepare questions for insertion
    const questionsToInsert = questionsData.map((q: any) => ({
      text: q.text,
      subjectId: subjectId,
      questionTypeId: 'four-options',
      options: q.options,
      difficulty: q.difficulty || 'easy',
      points: q.points || (q.difficulty === 'easy' ? 10 : q.difficulty === 'medium' ? 15 : 20),
      timeLimit: q.timeLimit || 30,
    }));

    // Insert questions
    await Question.insertMany(questionsToInsert);

    console.log(`✅ تم إضافة ${questionsToInsert.length} سؤال جغرافي (4 خيارات)!`);
    console.log(`   - جميع الأسئلة من نوع: 4 خيارات`);
    
    process.exit(0);
  } catch (error) {
    console.error('❌ خطأ:', error);
    process.exit(1);
  }
};

seedGeographyFourOptions();
