import { QuestionType } from '../types/question.types';

export const HARDCODED_QUESTION_TYPES: QuestionType[] = [
  {
    id: 'fill-blank',
    name: 'Fill in the Blank',
    nameAr: 'املأ الفراغ ✏️',
    description: 'اكتب الإجابة الصحيحة في الفراغ',
    requiresOptions: false,
    requiresTextAnswer: true,
    supportsImage: false,
    supportsAudio: false,
    defaultTimeLimit: 40,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'four-options',
    name: '4 Options',
    nameAr: '4 خيارات 🎯',
    description: 'اختر الإجابة الصحيحة من 4 خيارات',
    requiresOptions: true,
    requiresTextAnswer: false,
    supportsImage: true,
    supportsAudio: false,
    defaultTimeLimit: 30,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'order-challenge',
    name: 'Order Challenge',
    nameAr: 'رتب الترتيب 📋',
    description: 'رتب العناصر بالترتيب الصحيح',
    requiresOptions: true,
    requiresTextAnswer: false,
    supportsImage: false,
    supportsAudio: false,
    defaultTimeLimit: 45,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'who-and-who',
    name: 'Who & Who',
    nameAr: 'من ومن 👥',
    description: 'وصّل شخصين مع إنجازين',
    requiresOptions: true,
    requiresTextAnswer: false,
    supportsImage: true,
    supportsAudio: false,
    defaultTimeLimit: 50,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
